### ISSUE TITLE
Examples of Keyboard API uses

### ISSUE THREAD

**Issue by bershanskiy** [WICG/keyboard-map#27]
Is there any site or live demo that uses Keyboard Map API?

Since regular keyboards and OS'es already support regular typing pretty well, I can imagine that this API is helpful for mapping non-text input onto the keyboard. For example, video games or music instruments. But I have never seen any demos that rely on Keyboard API.

**Comment by MelvinWM** [comment]
Both the lack of browser support apart from Chrome, as well as the "top-level global context" privacy requirement (since many web applications might be embedded in iframes), hinders usage.

**Comment by bershanskiy** [comment]
Closing this because this is just a question and not relly an issue.

**Comment by garykac** [comment]
To answer the original question, the primary use case for this API is for handling keyboard shortcuts in a locale-independent way.

`key` tells you what character the keypress generates, but includes modifiers, so is not good for handling shortcuts.
`code` tells you which physical key has been pressed, and is not affected by the current keyboard layout. Because of this you cannot present the user with a `code` and expect them to know which key that corresponds to.

The Keyboard API fills this gap by creating a mapping from a `code` value to a character string the the user can understand to identify the physical key on the keyboard. Note that this assumes that the current layout matches the values printed on the key caps.

Web-based games, for example, use this to handle keypresses and allow the player to remap keys. You can program your game to use WASD keys for movement but since some locales move the actual "W" "A" "S" and "D" keys around, this API allows you to find out which keys are in the WASD position on the current layout.
