### ISSUE TITLE
Privacy and fingerprinting concerns 

### ISSUE THREAD

**Issue by cynthia** [WICG/keyboard-map#8]
Brought up during TAG review: https://github.com/w3ctag/design-reviews/issues/238 and #4 

As noted in both the privacy section and the S&P self review - this does increase fingerprinting surface. (although it's not entirely impossible to replicate the same with a user input backlog, this makes it much easier)  

Very specific cases (QWERTY layout in a country where QWERTY is rare, or minority layouts such as DVORAK) have extremely high information gain on fingerprinting these demographics (although most likely not a large audience) - which begs the question whether or not this should be behind a permission.

The spec also notes that this should behave the same in both incognito and normal, which we didn't have consensus on - but is a point that probably needs to extra consideration, in the event this would be considered as a fingerprinting surface.

Would love to hear your feedback on this.

**Comment by hadleybeeman** [comment]
Specifically, we also talked about UAs that might want to prioritise privacy. You are in a position to give them more information about the potential privacy risks and ways to mitigate them (like different behaviour in private/incognito mode or putting this behind a permission, for example). I think it would be useful to see that thinking reflected somewhere -- either in the spec or in the explainer.

**Comment by slightlyoff** [comment]
The potential for gating this via a permission is another good argument for returning a `Promise`

**Comment by garykac** [comment]
We updated the API return a Promise, and I've updated the section about privacy to give more information about fingerprinting.

The API is the same for normal and incognito because there is no obviously better thing to do in incognito. Always returning US-QWERTY (for example) is sometimes better (e.g., for everyone in the US), and sometimes worse (e.g., for people incognito in the UK, or France).

I've opened #16 to track the incognito issue.
